services:
  reservation:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev reservations
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev auth
